words = [
        ["Alabama", "Bama"],
        ["Alaska", "AK"],
        ["American Samoa", "Samoa"],
        ["Arizona", "AZ", "Ariz"],
        ["Arkansas", "Ark"],
        ["California", "Calif", "Cali", "Cal"],
        ["CNMI", "Saipan", "Mariana", "Northern Mariana", "Pacific", "NorthernMariana"],
        ["Colorado", "Colo", "Color"],
        ["Connecticut", "CT", "Conn"],
        ["Delaware", "Del"],
        ["Florida", "FL", "Fla"],
        ["Georgia", "Peach"],
        ["Guam"],
        ["Hawaii", "Aloha"],
        ["Idaho", "Potato"],
        ["Illinois", "IL", "Ill"],
        ["Indiana", "Ind"],
        ["Iowa"],
        ["Kansas", "KS", "Kan"],
        ["Kentucky", "KY"],
        ["Louisiana"],
        ["Maine", "Vacationland", "Vacation"],
        ["Maryland", "MD"],
        ["Massachusetts", "Mass"],
        ["Michigan", "Mich", "Pure"],
        ["Minnesota", "MN", "Minn"],
        ["Mississippi", "MS"],
        ["Missouri"],
        ["Montana", "MT"],
        ["Nebraska", "Neb"],
        ["Nevada", "NV", "Nev"],
        ["New Hampshire", "NH", "N.H.", "Hampshire", "NewHampshire"],
        ["New Jersey", "NJ", "N.J.", "Jersey", "Garden", "NewJersey"],
        ["New Mexico", "NM", "N.M.", "Mexico", "Enchantment", "NewMexico"],
        ["New York", "NY", "N.Y.", "York", "NewYork"],
        ["North Carolina", "N.C.", "NorthCarolina"],
        ["North Dakota", "ND", "N.D.", "NorthDakota", "N.Dakota", "NDakota"],
        ["Ohio"],
        ["Oklahoma", "OK", "Okla"],
        ["Oregon", "Ore"],
        ["Pennsylvania", "PA", "Penn", "Penna"],
        ["Puerto Rico", "PuertoRico", "Puerto", "Rico"],
        ["Rhode Island", "R.I.", "RhodeIsland", "Rhode"],
        ["South Carolina", "SC", "S.C.", "SouthCarolina"],
        ["South Dakota", "SD", "S.D.", "SouthDakota", "S.Dak", "S.Dakota", "SDak", "SDakota"],
        ["Tennessee", "TN", "Tenn"],
        ["Texas", "TX", "Tex"],
        ["Virgin", "Islands", "VirginIslands"],
        ["Utah"],
        ["Vermont", "VT"],
        ["Virginia"],
        ["Washington", "WA", "Wash"],
        ["Columbia", "Washington DC", "Washington D.C.", "WashingtonDC"],
        ["West Virginia", "WV", "W.Va.", "WestVirginia"],
        ["Wisconsin", "Wisc"],
        ["Wyoming", "WY", "Wyo"]
    ]
