words = [
        ["Alabama", "Bama"],
        ["Alaska", "Alas"],
        ["American Samoa", "Samoa"],
        ["Arizona", "Ariz"],
        ["Arkansas", "Ark"],
        ["California", "Calif", "Cali", "Cal"],
        ["CNMI", "Saipan", "Mariana", "Northern Mariana", "Pacific", "NorthernMariana"],
        ["Colorado", "Colo", "Color"],
        ["Connecticut", "Conn"],
        ["Delaware", "Del"],
        ["Florida", "Rida" "Fla"],
        ["Georgia", "Peach"],
        ["Guam"],
        ["Hawaii", "Aloha"],
        ["Idaho", "Potato"],
        ["Illinois", "Ill"],
        ["Indiana", "Ind"],
        ["Iowa"],
        ["Kansas", "Kan"],
        ["Kentucky", "Tucky"],
        ["Louisiana"],
        ["Maine", "Vacationland", "Vacation"],
        ["Maryland", "Mary"],
        ["Massachusetts", "Mass"],
        ["Michigan", "Mich", "Pure"],
        ["Minnesota", "Minn", "Sota"],
        ["Mississippi", "Sippi", "Missi"],
        ["Missouri", "Souri"],
        ["Montana"],
        ["Nebraska", "Neb"],
        ["Nevada", "Nev"],
        ["New Hampshire", "NH", "Hampshire", "NewHampshire"],
        ["New Jersey", "NJ", "N.J.", "Jersey", "Garden", "NewJersey"],
        ["New Mexico", "Mexico", "Enchantment", "NewMexico"],
        ["New York", "York", "NewYork"],
        ["North Carolina", "NorthCarolina"],
        ["North Dakota","N.Dak", "NDak", "NorthDakota", "N.Dakota", "NDakota"],
        ["Ohio"],
        ["Oklahoma","Okla"],
        ["Oregon", "Ore"],
        ["Pennsylvania", "Penn", "Penna"],
        ["Puerto Rico", "PuertoRico", "Puerto", "Rico"],
        ["Rhode Island", "R.I.", "RhodeIsland", "Rhode"],
        ["South Carolina", "SouthCarolina"],
        ["South Dakota","SouthDakota", "S.Dak", "S.Dakota", "SDak", "SDakota"],
        ["Tennessee", "Tenn"],
        ["Texas", "Tex"],
        ["Islands", "VirginIslands"],
        ["Utah"],
        ["Vermont"],
        ["Virginia"],
        ["Washington", "Wash"],
        ["Columbia", "Washington DC", "Washington D.C.", "WashingtonDC", "DC", "D.C"],
        ["West Virginia", "WV", "W.Va.", "WestVirginia", "West", "WVA", "W.Va"],
        ["Wisconsin", "Wisc"],
        ["Wyoming", "WY", "Wyo"]
    ]
